services:
  mongodb:
    image: mongo:7
    container_name: magamart-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: magamart
    ports:
      - '27017:27017'
    volumes:
      - magamart-mongodata:/data/db

volumes:
  magamart-mongodata:
